name: Update TVPass Playlist

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch:       

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # disable default token handling

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run tvpass.py
        run: python file/tvpass.py

      - name: Commit changes if any
        run: |
          git config user.name "albinchristo04"
          git config user.email "albinchristo04@users.noreply.github.com"
          git add TVPass.m3u
          git diff --cached --quiet || git commit -m "auto-update TVPass.m3u"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
